apiVersion: v1
kind: Pod
metadata:
  namespace: sqldb
  labels:
  name: db
spec:
  containers:
  - image: 334109771446.dkr.ecr.us-east-1.amazonaws.com/ass1-prod-db:v14.0
    name: db
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    ports:
    - containerPort: 3306
      name: mysql
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always