apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: sqldb
  name: db
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: db
        image: 334109771446.dkr.ecr.us-east-1.amazonaws.com/ass1-prod-db:v14.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always