apiVersion: v1
kind: Service
metadata:
  namespace: webapp
  name: webapp-service
  labels:
    app: employee
    version: v1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodeport: 30001
  selector:
    app: employee
    version: v1
