apiVersion: v1
kind: Service
metadata:
  namespace: webapp
  name: webapp-v2-service
  labels:
    app: employee
    version: v2
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  selector:
    app: employee
    version: v2